name: Upload APK Release
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Upload APK to Release
        uses: softprops/action-gh-release@v2
        with:
          files: Dental_Lab_Connect_AN*.apk
          tag_name: v1.0
          name: Dental Lab Connect v1.0
