name: Upload APK Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Upload APK
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0
          name: Dental Lab Connect v1.0
          files: '*.apk'
          
